@TPApi_HostAddress = https://localhost:7295


POST {{TPApi_HostAddress}}/food/processinput
Content-Type: application/json
[
    {
        "frontendId": 0,
        "name": "pizza",
        "weight": 250
    },
    {
        "frontendId": -4,
        "name": "kvarg låg fetthalt",
        "weight": -50
    },
    {
        "frontendId": -124,
        "name": "filmjölk tre procent",
        "weight": 0
    }
]