@TPApi_HostAddress = https://localhost:7295


POST {{TPApi_HostAddress}}/food/processinput
Content-Type: application/json
[
    {
        "frontendId": 0,
        "name": "kvarg",
        "weight": 0
    },
    {
        "frontendId": -4,
        "name": "musli",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "bär",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "pumpafrön",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "paranötter",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "rapsolja",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "pastasås",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "falafel",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "ärtor",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "ljust bröd",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "bregott",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "ost",
        "weight": 0
    },
    {
        "frontendId": -124,
        "name": "proteinpulver",
        "weight": 0
    }
]