@TPApi_HostAddress = https://localhost:7295


POST {{TPApi_HostAddress}}/food/processinput
Content-Type: application/json
[
    {
        "frontendId": 1,
        "name": "Potatis",
        "weight": 250
    },
    {
        "frontendId": 2,
        "name": "Nötkött",
        "weight": 150
    },
    {
        "frontendId": 3,
        "name": "basilika",
        "weight": 0
    }
]