// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPApi.Data;

#nullable disable

namespace TPApi.Migrations
{
    [DbContext(typeof(TPDbContext))]
    [Migration("20240816112655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPApi.Models.FoodEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodEmbeddings");
                });

            modelBuilder.Entity("TPApi.Models.FoodProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("A")
                        .HasColumnType("float");

                    b.Property<double>("B1")
                        .HasColumnType("float");

                    b.Property<double>("B12")
                        .HasColumnType("float");

                    b.Property<double>("B2")
                        .HasColumnType("float");

                    b.Property<double>("B3")
                        .HasColumnType("float");

                    b.Property<double>("B6")
                        .HasColumnType("float");

                    b.Property<double>("B9")
                        .HasColumnType("float");

                    b.Property<double>("C")
                        .HasColumnType("float");

                    b.Property<double>("D")
                        .HasColumnType("float");

                    b.Property<double>("E")
                        .HasColumnType("float");

                    b.Property<double>("Jarn")
                        .HasColumnType("float");

                    b.Property<double>("Jod")
                        .HasColumnType("float");

                    b.Property<double>("Kalcium")
                        .HasColumnType("float");

                    b.Property<double>("Kalium")
                        .HasColumnType("float");

                    b.Property<double>("Magnesium")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Selen")
                        .HasColumnType("float");

                    b.Property<double>("Zink")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FoodProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
